[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

# Cache static assets for 1 year
[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 year
[[headers]]
for = "*.jpg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.jpeg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.png"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.webp"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.avif"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache fonts for 1 year
[[headers]]
for = "*.woff2"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.woff"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache other static assets
[[headers]]
for = "*.svg"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.ico"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# HTML files - shorter cache with revalidation
[[headers]]
for = "*.html"

[headers.values]
Cache-Control = "public, max-age=3600, must-revalidate"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
