/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/chat': RouteRecordInfo<'/chat', '/chat', Record<never, never>, Record<never, never>>,
    '/chat-zh': RouteRecordInfo<'/chat-zh', '/chat-zh', Record<never, never>, Record<never, never>>,
    '/demos': RouteRecordInfo<'/demos', '/demos', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/photos': RouteRecordInfo<'/photos', '/photos', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/animated-svg-logo': RouteRecordInfo<'/posts/animated-svg-logo', '/posts/animated-svg-logo', Record<never, never>, Record<never, never>>,
    '/posts/attention-is-all-they-need': RouteRecordInfo<'/posts/attention-is-all-they-need', '/posts/attention-is-all-they-need', Record<never, never>, Record<never, never>>,
    '/posts/color-scheme-for-vscode-ext': RouteRecordInfo<'/posts/color-scheme-for-vscode-ext', '/posts/color-scheme-for-vscode-ext', Record<never, never>, Record<never, never>>,
    '/posts/domain-email': RouteRecordInfo<'/posts/domain-email', '/posts/domain-email', Record<never, never>, Record<never, never>>,
    '/posts/i-am-a-slow-thinker': RouteRecordInfo<'/posts/i-am-a-slow-thinker', '/posts/i-am-a-slow-thinker', Record<never, never>, Record<never, never>>,
    '/posts/leanring-out-loud': RouteRecordInfo<'/posts/leanring-out-loud', '/posts/leanring-out-loud', Record<never, never>, Record<never, never>>,
    '/posts/photos-page': RouteRecordInfo<'/posts/photos-page', '/posts/photos-page', Record<never, never>, Record<never, never>>,
    '/posts/sliding-enter-animation': RouteRecordInfo<'/posts/sliding-enter-animation', '/posts/sliding-enter-animation', Record<never, never>, Record<never, never>>,
    '/posts/sports-and-focus': RouteRecordInfo<'/posts/sports-and-focus', '/posts/sports-and-focus', Record<never, never>, Record<never, never>>,
    '/posts/the-making-of-my-personal-blog': RouteRecordInfo<'/posts/the-making-of-my-personal-blog', '/posts/the-making-of-my-personal-blog', Record<never, never>, Record<never, never>>,
    '/projects_underconstruct': RouteRecordInfo<'/projects_underconstruct', '/projects_underconstruct', Record<never, never>, Record<never, never>>,
    '/quotes': RouteRecordInfo<'/quotes', '/quotes', Record<never, never>, Record<never, never>>,
  }
}
