import {
  createLocalFontProcessor,
} from '@unocss/preset-web-fonts/local'
import {
  defineConfig,
  presetAttributify,
  presetIcons,
  presetWebFonts,
  presetWind3,
  transformerDirectives,
} from 'unocss'

export default defineConfig({
  shortcuts: [
    {
      'bg-base': 'bg-white dark:bg-black',
      'color-base': 'text-black dark:text-white',
      'border-base': 'border-[#8884]',
    },
    [/^btn-(\w+)$/, ([_, color]) => `op50 px2.5 py1 transition-all duration-200 ease-out no-underline! hover:(op100 text-${color} bg-${color}/10) border border-base! rounded`],
  ],
  rules: [
    [/^slide-enter-(\d+)$/, ([_, n]) => ({
      '--enter-stage': n,
    })],
  ],
  presets: [
    presetIcons({
      mode: 'mask',
      prefix: 'i-',
      warn: true,
      autoInstall: false,
      extraProperties: {
        'display': 'inline-block',
        'height': '1.2em',
        'width': '1.2em',
        'vertical-align': 'text-bottom',
      },
    }),
    presetAttributify(),
    presetWind3(),
    presetWebFonts({
      fonts: {
        sans: 'Inter',
        mono: 'DM Mono',
        condensed: 'Roboto Condensed',
        wisper: 'Bad Script',
      },
      processors: createLocalFontProcessor(),
    }),
  ],
  transformers: [
    transformerDirectives(),
  ],
  safelist: [
    // Carbon icons
    'i-carbon-accumulation-precipitation',
    'i-carbon-ai-results-high',
    'i-carbon-angle',
    'i-carbon-app-switcher',
    'i-carbon-arrow-up-right',
    'i-carbon-at',
    'i-carbon-cafe',
    'i-carbon-campsite',
    'i-carbon-chart-multitype',
    'i-carbon-checkbox',
    'i-carbon-checkbox-checked',
    'i-carbon-checkmark',
    'i-carbon-chemistry',
    'i-carbon-cics-region-routing',
    'i-carbon-cloud-lightning',
    'i-carbon-code',
    'i-carbon-color-palette',
    'i-carbon-copy',
    'i-carbon-data-vis-1',
    'i-carbon-data-vis-4',
    'i-carbon-delivery-parcel',
    'i-carbon-direction-merge',
    'i-carbon-earth',
    'i-carbon-earth-southeast-asia',
    'i-carbon-face-wink',
    'i-carbon-favorite',
    'i-carbon-flash',
    'i-carbon-function',
    'i-carbon-ibm-cloud-event-notification',
    'i-carbon-ibm-watson-language-translator',
    'i-carbon-ibm-watsonx-code-assistant',
    'i-carbon-ibm-watsonx-code-assistant-for-z-refactor',
    'i-carbon-keyboard',
    'i-carbon-map',
    'i-carbon-music',
    'i-carbon-package',
    'i-carbon-paint-brush',
    'i-carbon-plane-sea',
    'i-carbon-plug',
    'i-carbon-printer',
    'i-carbon-qr-code',
    'i-carbon-registration',
    'i-carbon-row-insert',
    'i-carbon-run',
    'i-carbon-satellite-weather',
    'i-carbon-scan-alt',
    'i-carbon-scatter-matrix',
    'i-carbon-search-locate',
    'i-carbon-search-locate-mirror',
    'i-carbon-settings-check',
    'i-carbon-share-knowledge',
    'i-carbon-spine-label',
    'i-carbon-svg',
    'i-carbon-table',
    'i-carbon-template',
    'i-carbon-terminal',
    'i-carbon-test-tool',
    'i-carbon-text-align-mixed',
    'i-carbon-text-line-spacing',
    'i-carbon-theater',
    'i-carbon-thumbnail-2',
    'i-carbon-time',
    'i-carbon-tools-alt',
    'i-carbon-translate',
    'i-carbon-type-pattern',
    'i-carbon-unknown',
    'i-carbon-windy-strong',
    'i-carbon-workspace-import',

    // Other icon collections
    'i-codicon-package',
    'i-heroicons-solid-cursor-click',
    'i-ion-logo-pwa',
    'i-ion-logo-twitter',
    'i-la-glasses-solid',
    'i-logos-nuxt-icon',
    'i-logos-vitejs',
    'i-mdi-git',
    'i-mdi-hexagon-slice-4',

    // Phosphor icons
    'i-ph-cow-duotone',
    'i-ph-cow-fill',
    'i-ph-github-logo-duotone',
    'i-ph-github-logo-fill',
    'i-ph-hand-heart-duotone',
    'i-ph-hand-heart-fill',
    'i-ph-heart-duotone',
    'i-ph-heart-fill',
    'i-ph-lightning-duotone',
    'i-ph-lightning-fill',
    'i-ph-rocket-launch-duotone',
    'i-ph-rocket-launch-fill',
    'i-ph-user',

    // Pixel art icons
    'i-pixelarticons-power',

    // Remix icons
    'i-ri-arrow-right-up-line',
    'i-ri-arrow-up-line',
    'i-ri-calendar-event-fill',
    'i-ri-calendar-event-line',
    'i-ri-camera-3-line',
    'i-ri-download-2-line',
    'i-ri-file-list-3-line',
    'i-ri-lightbulb-line',
    'i-ri-menu-2-fill',
    'i-ri-moon-line',
    'i-ri-play-large-line',
    'i-ri-presentation-fill',
    'i-ri-pushpin-line',
    'i-ri-reactjs-fill',
    'i-ri-sun-line',
    'i-ri-time-line',
    'i-ri-twitter-x-fill',

    // Simple icons
    'i-simple-icons-eslint',
    'i-simple-icons-github',
    'i-simple-icons-linkedin',
    'i-simple-icons-postcss',
    'i-simple-icons-vite',
    'i-simple-icons-whatsapp',

    // Solar icons
    'i-solar-black-hole-line-duotone',

    // Tabler icons
    'i-tabler-currency-dollar',

    // Teenyicons
    'i-teenyicons-git-outline',
    'i-teenyicons-markdown-outline',

    // UIM icons
    'i-uim-instagram',
    'i-uim-vuejs',
    'i-uim-web-grid',
  ],
})
